spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myboard
    username: ohgiraffers
    password: ohgiraffers
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: dev